#!/usr/bin/env bash
# This script does some memage and deletes a file it created upon receiving certain signals.
echo $$ > "/var/run/holbertonscript.pid"
trap "echo 'Y U no love me?!'" SIGINT
trap 'rm "/var/run/holbertonscript.pid"; kill -s KILL "$$"' SIGQUIT
trap 'rm "/var/run/holbertonscript.pid"; echo "I hate the kill command"; kill -s KILL "$$"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep
done
