#!/usr/bin/env bash
# This script is an endless loop which prints "to infinity and beyond" every 2s
rmndip () {
    rm -rf /var/run/myscript.pid
    exit
}

trap 'echo "I hate the kill command"; rmndip' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rmndip' SIGQUIT

echo "$$"  > /var/run/my.pid

while BUZZLIGHTYEAR="To infinity and beyond"
        do echo "$BUZZLIGHTYEAR"
           sleep 2
done
